# Generated by Django 2.1.7 on 2019-06-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry_special_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='操作的表名')),
                ('opr_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='操作类型')),
                ('opr_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='操作名称')),
            ],
            options={
                'db_table': 'entry_special_info',
            },
        ),
        migrations.CreateModel(
            name='enum_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum_no', models.IntegerField(verbose_name='枚举编号')),
                ('enum_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='枚举类型')),
                ('enum_subtype', models.CharField(blank=True, max_length=50, null=True, verbose_name='枚举二级类型')),
                ('enum_value', models.CharField(blank=True, max_length=120, null=True, verbose_name='枚举值')),
                ('desc', models.CharField(blank=True, max_length=120, null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'enum_info',
            },
        ),
        migrations.CreateModel(
            name='v_user',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('wechat_no', models.CharField(max_length=60, unique=True, verbose_name='微信号')),
                ('id_type', models.IntegerField(verbose_name='证件类型')),
                ('id_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='证件号码')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码')),
                ('user_level', models.IntegerField(verbose_name='用户级别')),
                ('status', models.CharField(choices=[('on', '可用'), ('close', '不可用')], max_length=10, verbose_name='用户状态')),
                ('self_proc_illegal', models.CharField(choices=[('on', '可用'), ('close', '不可用')], max_length=10, verbose_name='用户状态')),
                ('desc', models.TextField(max_length=120, verbose_name='描述')),
            ],
            options={
                'db_table': 'v_user',
            },
        ),
    ]
