# Generated by Django 2.1.7 on 2019-06-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferry_management_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wechat_access_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=120, verbose_name='access token')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'db_table': 'wechat_access_token',
            },
        ),
    ]
