# Generated by Django 2.1.7 on 2019-06-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferry_management_platform', '0003_delete_wechat_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='wechat_access_token',
            fields=[
                ('access_token', models.CharField(max_length=240, primary_key=True, serialize=False, verbose_name='access token')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'db_table': 'wechat_access_token',
            },
        ),
    ]
