# Generated by Django 2.1.7 on 2019-06-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferry_management_platform', '0004_wechat_access_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wechat_access_token',
        ),
    ]
