# Generated by Django 2.1.7 on 2019-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferry_management_platform', '0007_delete_wechat_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='wechat_access_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=240, verbose_name='access token')),
                ('url', models.URLField(verbose_name='service url')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'db_table': 'wechat_access_token',
            },
        ),
    ]
